#!/bin/bash

# Direct cleanup using Todoist API
# Run this to clean up duplicate tasks

echo "========================="
echo "TODOIST CLEANUP REQUIRED"
echo "========================="
echo ""
echo "You have 19 duplicate tasks in Todoist that need to be deleted."
echo ""
echo "To clean them up:"
echo ""
echo "1. Get your Todoist API token from:"
echo "   https://todoist.com/app/settings/integrations/developer"
echo ""
echo "2. Run this command with your token:"
echo ""
echo "   export TODOIST_API_TOKEN='your-token-here'"
echo ""
echo "3. Then run the cleanup:"
echo ""
echo "   ./scripts/cleanup-duplicates.sh"
echo ""
echo "Tasks to be deleted (duplicates):"
echo "  - 5x Cancel Cursor"
echo "  - 5x Downgrade Claude"  
echo "  - 5x Rodar migration do serviço"
echo "  - 4x Upgrade GPT"
echo ""
echo "Tasks to be kept (originals):"
echo "  - 1x Cancel Cursor (ID: 9472645434)"
echo "  - 1x Downgrade Claude (ID: 9472645764)"
echo "  - 1x Rodar migration (ID: 9468010927)"
echo "  - 1x Upgrade GPT (ID: 9472646165)"
echo "  - 1x Another D1 test task (ID: 9475795780)"
echo "  - 1x Third D1 test (ID: 9475795853)"